CREATE TABLE if not exists tb_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) not null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) not null,
    password varchar(255) not null,
    account_locked boolean not null,
    enabled boolean not null,
    created_date timestamp(6) not null,
    last_modified_date timestamp(6) null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_user_roles (
    users_id bigint not null,
    roles_id bigint not null,
    primary key (users_id, roles_id),
    foreign key (users_id) references tb_user(id),
    foreign key (roles_id) references tb_role(id)
);